version: "3.2"
services:

  mongo:
   container_name: mongo_mein_chanda
   image: mongo:4
   ports:
     - "27017:27017"
   volumes:
     - type: volume
       source: mein-chanda-volume
       target: /data/db

  keycloak:
    container_name: keycloak_mein_chanda
    image: jboss/keycloak:8.0.0
    ports:
      - "10080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin123

volumes:
  mein-chanda-volume:
